# Generated by Django 4.2.18 on 2025-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=50)),
                ('pub_year', models.PositiveIntegerField(verbose_name='Year Published')),
                ('summary', models.TextField(default='', max_length=500)),
                ('in_stock', models.BooleanField(default=False)),
                ('book_cover', models.ImageField(upload_to='media/book_covers')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=240)),
            ],
        ),
    ]
