# Generated by Django 4.2.18 on 2025-04-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13, verbose_name='ISBN'),
        ),
    ]
