# Generated by Django 4.2.18 on 2025-04-28 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending', '0002_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.collection'),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
