# Generated by Django 4.2.18 on 2025-02-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_remove_book_genres_book_genre_alter_book_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(default='Frankenstein tells the story of gifted scientist Victor Frankenstein who succeeds in giving life to a being of his own creation. However, this is not the perfect specimen he imagines that it will be, but rather a hideous creature who is rejected by Victor and mankind in general.', max_length=250),
            preserve_default=False,
        ),
    ]
