# Generated by Django 4.2.18 on 2025-02-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='C:/Users/Patricio/Pictures/Saved Pictures/frankenstein_cover.jpg', upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
