# Generated by Django 4.2.18 on 2025-03-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_auto_20250329_1131'),
        ('lending', '0003_book_total_available_book_total_copies_request_and_more'),
    ]

    operations = [
    ]
