# Generated by Django 4.2.18 on 2025-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_private_collection',
            field=models.BooleanField(default=False),
        ),
    ]
