# Generated by Django 4.2.18 on 2025-04-29 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_alter_book_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/alternate_covers')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_covers', to='lending.book')),
            ],
        ),
    ]
