# Generated by Django 4.2.18 on 2025-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_merge_20250330_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
