# Generated by Django 4.2.18 on 2025-04-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0004_book_in_private_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_private_collection',
        ),
    ]
