# Generated by Django 4.2.18 on 2025-04-13 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lending', '0005_remove_book_in_private_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
