# Generated by Django 4.2.18 on 2025-02-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_alter_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(upload_to='media/book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
