# Generated by Django 4.2.18 on 2025-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_alternatecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternatecover',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alternate_covers/'),
        ),
    ]
