# Generated by Django 4.2.18 on 2025-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_collection_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
