# Generated by Django 4.2.18 on 2025-02-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_alter_book_book_cover_alter_book_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='book_genre',
        ),
    ]
