# Generated by Django 4.2.18 on 2025-04-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')]),
        ),
    ]
