# Generated by Django 4.2.18 on 2025-02-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_alter_book_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
    ]
