# Generated by Django 4.2.18 on 2025-02-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
    ]
