# Generated by Django 4.2.18 on 2025-04-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
