# Generated by Django 4.2.18 on 2025-04-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
