# Generated by Django 4.2.18 on 2025-02-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_alter_book_book_author_alter_book_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
    ]
